# This script is used to precompile vignettes and should be run for
# each new version of the package

# Get current wd (to restore later)
old_wd <- getwd()
# Set wd to vignettes to avoid saving to base directory
setwd("vignettes/")
# Precompile vignettes
library(knitr)
knit("./source/_geologic-map.Rmd",
     "geologic-map.Rmd")
knit("./source/_geological-completeness.Rmd",
     "geological-completeness.Rmd")
knit("./source/_stratigraphic-column.Rmd",
     "stratigraphic-column.Rmd")

# Build vignettes
library(devtools)
build_vignettes()

# x = vignette file name including file extension (e.g. "stratigraphic-column.Rmd")
read_only <- function(x) {
  tmp <- file(x)
  writeLines(c(paste0("# Generated by vignettes/precompile.R: do not edit by hand. ",
                      "Please edit source in vignettes/source/", x),
               readLines(x)), tmp)
  close(tmp)
}
# Add read only info
read_only("geologic-map.Rmd")
read_only("geological-completeness.Rmd")
read_only("stratigraphic-column.Rmd")
rm(read_only)

# Restore wd
setwd(old_wd)

